name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a feature!**
        Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? What is missing in the current implementation?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen
      placeholder: Describe the solution you'd like...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Describe the main use cases or scenarios where this feature would be valuable
      placeholder: Who will use this feature and how?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered (optional)
      placeholder: What other approaches could work?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocks core functionality)
        - High (significant improvement)
        - Medium (nice to have)
        - Low (minor enhancement)
      default: 2
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: Any ideas on how this could be implemented? (optional)
      placeholder: Technical suggestions, APIs, libraries, etc.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups (optional)
    validations:
      required: false
