name: Security Vulnerability
description: Report a security vulnerability or issue
title: "[SECURITY] "
labels: ["security", "vulnerability", "needs-triage"]
assignees:
  - jeremy
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report

        **⚠️ IMPORTANT:** If this is a critical security vulnerability, please consider reporting it privately via:
        
        - **GitHub Security Advisory:** [Report privately](https://github.com/Delqhi/BIOMETRICS/security/advisories/new)
        - **Email:** security@biometrics.dev
        - **Security Form:** https://biometrics.dev/security/report

        For more information, please read our [Security Policy](../../SECURITY.md).

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical (CVSS 9.0-10.0) - Remote code execution, auth bypass
        - High (CVSS 7.0-8.9) - Significant data exposure, privilege escalation
        - Medium (CVSS 4.0-6.9) - Limited impact, requires authentication
        - Low (CVSS 0.1-3.9) - Minor issue, minimal impact
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the vulnerability
      placeholder: |
        What is the vulnerability?
        How can it be exploited?
        What is the potential impact?
    validations:
      required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of BIOMETRICS are affected?
      placeholder: "e.g., 1.0.0, 0.9.x, all versions"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe the expected secure behavior
    validations:
      required: true

  - type: dropdown
    id: exploit-available
    attributes:
      label: Exploit Availability
      description: Is there a known exploit available for this vulnerability?
      options:
        - "No - Not aware of any exploits"
        - "Yes - Public exploit available"
        - "Yes - Exploit in the wild"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept (Optional)
      description: If available, provide a proof of concept or demonstration
      placeholder: |
        ```bash
        # Example exploit code or commands
        ```
      render: shell
    validations:
      required: false

  - type: dropdown
    id: cvss-vector
    attributes:
      label: CVSS v3.1 Vector (Optional)
      description: If you have calculated a CVSS score, provide the vector string
      options:
        - "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H (Critical)"
        - "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H (High)"
        - "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L (Medium)"
        - "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:L (Low)"
        - "Other (specify in description)"
        - "Not calculated"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, references, or context
      placeholder: |
        - Related CVEs
        - References to similar vulnerabilities
        - Screenshots or logs
        - Suggested fix (if any)
    validations:
      required: false

  - type: dropdown
    id: disclosure-preference
    attributes:
      label: Disclosure Preference
      description: How would you like to be credited in the public advisory?
      options:
        - "Full name/handle (e.g., John Doe @johndoe)"
        - "Anonymous"
        - "Organization only"
        - "Discuss with security team"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we contact you for follow-up questions?
      placeholder: "email@example.com or @username"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this report, you agree to follow our responsible disclosure process
      options:
        - label: I agree to keep this vulnerability confidential until a patch is released
          required: true
        - label: I will not exploit this vulnerability for malicious purposes
          required: true
        - label: I understand that the security team may need to contact me for additional information
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## What Happens Next?

        1. **Acknowledgment:** You will receive an acknowledgment within 24 hours
        2. **Initial Assessment:** Our security team will assess the vulnerability within 7 days
        3. **Regular Updates:** You will receive updates every 7 days during investigation
        4. **Resolution:** Timeline depends on severity (see [Security Policy](../../SECURITY.md))
        5. **Public Disclosure:** Advisory published after patch release (typically 30 days)

        **Thank you for helping keep BIOMETRICS secure!** 🙏

        For more information, see:
        - [Security Policy](../../SECURITY.md)
        - [Security Procedures](docs/SECURITY-PROCEDURES.md)
        - [Contributing Guide](.github/CONTRIBUTING.md)
