openapi: 3.0.3
info:
  title: BIOMETRICS Enterprise API
  description: Single Source of Truth for Frontend/Backend Communication. DO NOT DEVIATE.
  version: 1.0.0
  contact:
    name: API Architecture Team

servers:
  - url: /api/v1
    description: Primary API version 1 routing

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      required:
        - error
        - code
      properties:
        error:
          type: string
          description: Human readable error message
        code:
          type: string
          description: Internal error code for frontend mapping
        trace_id:
          type: string
          description: Correlation ID for Observability Logging

    User:
      type: object
      required:
        - id
        - email
        - created_at
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
          enum: [admin, user, auditor]
        created_at:
          type: string
          format: date-time

security:
  - BearerAuth: []

paths:
  /health:
    get:
      summary: System Health Check
      description: Returns 200 if Go Backend and Supabase are fully operational.
      security: []
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "operational"
                  database:
                    type: string
                    example: "connected"
        '503':
          description: System degradation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/me:
    get:
      summary: Get Current User Profile
      description: Fetches the profile of the authenticated user based on JWT.
      responses:
        '200':
          description: Successfully retrieved user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
